services:
  msolsys-frontend:
    image: msolsys_backend:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.msolsys_frontend.rule=Host(`msolsys.com`) || Host(`www.msolsys.com`)"
      - "traefik.http.services.msolsys_frontend.loadbalancer.server.port=443"
      - "traefik.http.routers.msolsys_frontend.entrypoints=websecure"
      - "traefik.http.routers.msolsys_frontend.tls=true"
      - "traefik.http.routers.msolsys_frontend.tls.certresolver=myresolver"
    networks:
      - default
      - traefik
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      
  msolsys-backend:
    image: msolsys_frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: msolsys_backend
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


networks:
  traefik:
    name: traefik
    external: true