server {
    listen 443;

    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
    add_header Cross-Origin-Opener-Policy "same-origin" always;
    add_header Cross-Origin-Resource-Policy "same-origin" always;
    
    client_max_body_size 10M;

    location /favicon.ico
    {
        autoindex off;
        alias /static/favicon.ico;
    }

    location = /index.html
    {
        alias /static/index.html;
        add_header Cache-Control "no-store";
        expires -1;
    }

    location /
    {
        autoindex off;
        alias /static/;
    }



    location /api/
    {
        proxy_pass http://msolsys-backend:80;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass_request_headers on;
        proxy_set_header   Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
    
    