server {
    listen 443;

    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
    add_header Cross-Origin-Opener-Policy "same-origin" always;
    add_header Cross-Origin-Resource-Policy "same-origin" always;
    
    client_max_body_size 10M;

    location /favicon.ico
    {
        autoindex off;
        alias /static/favicon.ico;
    }

    location /
    {
        autoindex off;
        alias /static/;
    }
}
    
    